### ISSUE TITLE
Planning to upgrade?

### ISSUE THREAD

**Issue by ghost** [BradKwon/Kwon.Mapbox.Android#1]
Hi,
First: you are a lifesaver! 👍 

Second, aquestion: do you plan to upgrade this binding to support the latest version (1.1.0) of MapBox for Android?

**Comment by BradKwon** [comment]
Hi @lfongaroScp, thank you. I am planning to do it in January. I cannot tell the exact date for the release but will start it.

**Comment by ghost** [comment]
Hi,

Unfortunately there is a bug in the version you bind in Android R
https://github.com/mapbox/mapbox-gl-native-android/issues/425

Are you still planning to upgrade the binding in January?

**Comment by BradKwon** [comment]
Hi @lfongaroScp, I updated bindings to v1.0.1 however, am still working on getting the sample app updated. If you want to use bindings before the sample app done, of course you can. And you can report or even tackle the issues followed. I will let you know when I finish the sample app update. Thanks.

**Comment by BradKwon** [comment]
I've encountered Kotlin coroutine exception when I tried to initialize mapbox navigation in the sample app.
I hope someone can advise or fix this error.

The error is:

`java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'`

I used Microsoft's kotlinx-coroutines-android binding but it is v1.3.4, which is lower version than required from native Mapbox library (v1.3.9)

I tried to set proguard rules there but didn't work so I assume that I have to wait until a newer version of this binding comes.

Therefore, unfortunately, v1.0.1 of this binding is useless. Please use v0.42.6 if you don't need new features.

**Comment by BradKwon** [comment]
I close this issue as upgrading to v1.0.1 failed. No plan for now.

**Comment by ghost** [comment]
Sorry, I have no idea how to resolve that problem :-(
