### ISSUE TITLE
Xamarin.Android Compilation issue

### ISSUE THREAD

**Issue by bbenetskyy** [BradKwon/Kwon.Mapbox.Android#3]
Hi, this is issue 1 of 3.

When I add `0.42.6` into Android Support project created from scratch I've got 5-6 errors.

When I add `1.0.1.3` into Android X project created from scratch I've got just the same 5-6 errors.

```
  Xamarin.Android.Legacy.targets(300, 5): [XA2002] Can not resolve reference: `GoogleGson`, referenced by `Kwon.Mapbox.*`. Please add a NuGet package or assembly reference for `GoogleGson`, or remove the reference to `Kwon.Mapbox.*`.
```

What should I do to make it run?

**Comment by BradKwon** [comment]
Hi @bbenetskyy , I have tried both cases on my machine however, didn't get any errors. I also created an empty Android project and tried it.

Sounds like adding GoogleGson nuget to your project might help.
