### ISSUE TITLE
MapboxNavigation.UI.Droid.TestApp can't be compiled

### ISSUE THREAD

**Issue by bbenetskyy** [BradKwon/Kwon.Mapbox.Android#4]
Hi, issue 2 of 3.

`MapboxNavigation.UI.Droid.TestApp` application at master branch can't be compiled at Visual Studio fo Mac or at Rider IDE.

![image](https://user-images.githubusercontent.com/8330262/116249481-293bf080-a76d-11eb-8532-123838dbda72.png)

**Comment by BradKwon** [comment]
Hi @bbenetskyy , looks the related issue like issue 1. I tried building that sample project and also no build error.
You can try adding GoogleGson nuget manually if it will solve that issue. Otherwise, it might be related to packages.config/PackageReference.
